2019-06-24T09:06:10.592Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:10051 failed to connect: 14 UNAVAILABLE: Connect Failed {}$
2019-06-24T09:06:13.886Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:10051 failed to connect: 14 UNAVAILABLE: Connect Failed {}$
2019-06-24T09:06:17.171Z ERROR   :HLFConnectionManager     :fabric-client()           [Remote.js]: Error: Failed to connect before the deadline {}$
2019-06-24T09:06:27.258Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:10051 failed to connect: 14 UNAVAILABLE: Connect Failed {}$
2019-06-24T09:06:30.466Z ERROR   :HLFConnectionManager     :fabric-client()           [Remote.js]: Error: Failed to connect before the deadline {}$
2019-06-24T09:06:30.468Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Failed to connect before the deadline
    at checkState (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:838:16) {}$
2019-06-24T09:58:48.339Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:10051 failed to connect: 14 UNAVAILABLE: Connect Failed {}$
2019-06-24T09:58:51.853Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:10051 failed to connect: 14 UNAVAILABLE: Connect Failed {}$
2019-06-24T09:58:55.101Z ERROR   :HLFConnectionManager     :fabric-client()           [Remote.js]: Error: Failed to connect before the deadline {}$
2019-06-24T09:59:05.921Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:10051 failed to connect: 14 UNAVAILABLE: Connect Failed {}$
2019-06-24T09:59:09.075Z ERROR   :HLFConnectionManager     :fabric-client()           [Remote.js]: Error: Failed to connect before the deadline {}$
2019-06-24T09:59:09.076Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Failed to connect before the deadline
    at checkState (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:838:16) {}$
2019-06-24T10:12:44.477Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: timeout expired while starting chaincode iot-network:0.0.1 for transaction
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T10:25:21.411Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: timeout expired while starting chaincode iot-network:0.0.1 for transaction
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T10:28:14.645Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: timeout expired while starting chaincode iot-network:0.0.1 for transaction
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T10:53:25.965Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:10051 failed to connect: 14 UNAVAILABLE: Connect Failed {}$
2019-06-24T10:53:31.031Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T10:53:31.093Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T10:53:33.473Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:10051 failed to connect: 14 UNAVAILABLE: Connect Failed {}$
2019-06-24T10:53:35.300Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T10:53:36.725Z ERROR   :HLFConnectionManager     :fabric-client()           [Remote.js]: Error: Failed to connect before the deadline {}$
2019-06-24T10:53:46.262Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:10051 failed to connect: 14 UNAVAILABLE: Connect Failed {}$
2019-06-24T10:53:49.609Z ERROR   :HLFConnectionManager     :fabric-client()           [Remote.js]: Error: Failed to connect before the deadline {}$
2019-06-24T10:53:49.610Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Failed to connect before the deadline
    at checkState (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:838:16) {}$
2019-06-24T10:55:10.168Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: Failed to connect before the deadline {}$
2019-06-24T14:42:03.304Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.108:7051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:42:03.306Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.108:8051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:42:03.309Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:9051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:42:03.310Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:10051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:42:06.363Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.108:7051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:42:06.365Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.108:8051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:42:06.369Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:9051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:42:06.372Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:10051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:42:15.864Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.108:8051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:42:15.871Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.108:7051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:42:15.874Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:10051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:42:15.885Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:9051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:42:15.896Z WARN    :HLFConnection            :_checkEventHubStrategy()  No connected event hubs found, attempting to re-establish event hubs {}$
2019-06-24T14:42:15.954Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.108:8051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:42:15.959Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:10051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:42:15.961Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.108:7051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:42:15.968Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:9051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:46:25.119Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.108:7051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:46:25.121Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.108:8051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:46:25.125Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:9051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:46:25.128Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:10051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:46:25.365Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T14:46:25.366Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T14:46:27.789Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.108:7051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:46:27.790Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.108:8051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:46:27.795Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:9051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:46:27.797Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:10051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:46:27.993Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T14:46:27.994Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T14:46:35.335Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.108:7051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:46:35.337Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.108:8051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:46:35.342Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:9051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:46:35.344Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.109:10051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:46:35.358Z WARN    :HLFConnection            :_checkEventHubStrategy()  No connected event hubs found, attempting to re-establish event hubs {}$
2019-06-24T14:46:35.436Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.108:7051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:46:35.437Z WARN    :HLFConnection            :_connectToEventHubs()     event hub 192.168.56.108:8051 failed to connect: Received status message on the event stream. status:NOT_FOUND {}$
2019-06-24T14:55:48.095Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T14:55:48.104Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T14:55:50.769Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T14:55:50.772Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T14:55:50.772Z ERROR   :HLFConnection            :install()                 {"message":"Error trying install business network. Error: The business network is already installed on all the peers","stack":"Error: Error trying install business network. Error: The business network is already installed on all the peers\n    at HLFConnection.install (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:602:30)\n    at <anonymous>"}$
2019-06-24T15:31:25.608Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: timeout expired while starting chaincode iot-network:0.0.1 for transaction
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T15:31:36.489Z ERROR   :HLFConnectionManager     :fabric-client()           [Peer.js]: sendProposal - timed out after:2100000 {}$
2019-06-24T15:31:37.264Z ERROR   :HLFConnectionManager     :fabric-client()           [Peer.js]: sendProposal - timed out after:2100000 {}$
2019-06-24T15:31:37.264Z ERROR   :HLFConnectionManager     :fabric-client()           [Peer.js]: sendProposal - timed out after:2100000 {}$
2019-06-24T15:31:37.494Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:94:20)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) {}$
2019-06-24T15:31:37.887Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:94:20)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) {}$
2019-06-24T15:31:37.888Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:94:20)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) {}$
2019-06-24T15:31:39.972Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT {}$
2019-06-24T15:31:39.972Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT {}$
2019-06-24T15:31:39.972Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT {}$
2019-06-24T15:31:39.972Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: timeout expired while starting chaincode iot-network:0.0.1 for transaction {}$
2019-06-24T15:31:42.313Z ERROR   :HLFConnection            :start()                   {"message":"No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: REQUEST_TIMEOUT\nResponse from attempted peer comms was an error: Error: REQUEST_TIMEOUT\nResponse from attempted peer comms was an error: Error: REQUEST_TIMEOUT\nResponse from attempted peer comms was an error: Error: timeout expired while starting chaincode iot-network:0.0.1 for transaction","stack":"Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: REQUEST_TIMEOUT\nResponse from attempted peer comms was an error: Error: REQUEST_TIMEOUT\nResponse from attempted peer comms was an error: Error: REQUEST_TIMEOUT\nResponse from attempted peer comms was an error: Error: timeout expired while starting chaincode iot-network:0.0.1 for transaction\n    at HLFConnection._validatePeerResponses (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:855:19)\n    at HLFConnection._sendTransaction (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:778:37)\n    at HLFConnection.start (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:756:24)\n    at <anonymous>"}$
2019-06-24T15:45:18.260Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T15:45:19.802Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T15:45:39.036Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T15:45:39.151Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T15:45:39.153Z ERROR   :HLFConnection            :install()                 {"message":"Error trying install business network. Error: The business network is already installed on all the peers","stack":"Error: Error trying install business network. Error: The business network is already installed on all the peers\n    at HLFConnection.install (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:602:30)\n    at <anonymous>"}$
2019-06-24T16:05:14.936Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:05:15.069Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:05:23.489Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:05:23.522Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:05:34.547Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode with name 'iot-network' already exists
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:05:34.551Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode with name 'iot-network' already exists
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:05:34.554Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode with name 'iot-network' already exists
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:05:34.584Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode with name 'iot-network' already exists
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:43:01.367Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: timeout expired while starting chaincode iot-network:0.0.1 for transaction
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:43:07.072Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: timeout expired while starting chaincode iot-network:0.0.1 for transaction
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:43:16.435Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: timeout expired while starting chaincode iot-network:0.0.1 for transaction
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:43:20.135Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: timeout expired while starting chaincode iot-network:0.0.1 for transaction
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:44:27.090Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:44:27.306Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:44:33.683Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:44:34.066Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error installing chaincode code iot-network:0.0.1(chaincode /var/hyperledger/production/chaincodes/iot-network.0.0.1 exists)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:50:15.368Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '16704a8b4240258cf187bcc8f1e90bce64cd867ba9649680410e8d8fe7172e8f', must be activated (ACTIVATION_REQUIRED)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:50:15.369Z WARN    :HLFQueryHandler          :queryChaincode()          query payload returned an error: Error: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '16704a8b4240258cf187bcc8f1e90bce64cd867ba9649680410e8d8fe7172e8f', must be activated (ACTIVATION_REQUIRED) {}$
2019-06-24T16:50:15.370Z ERROR   :HLFConnection            :ping()                    {"message":"Error trying to ping. Error: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '16704a8b4240258cf187bcc8f1e90bce64cd867ba9649680410e8d8fe7172e8f', must be activated (ACTIVATION_REQUIRED)","stack":"Error: Error trying to ping. Error: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '16704a8b4240258cf187bcc8f1e90bce64cd867ba9649680410e8d8fe7172e8f', must be activated (ACTIVATION_REQUIRED)\n    at _checkRuntimeVersions.then.catch (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:886:34)\n    at <anonymous>"}$
2019-06-24T16:50:27.645Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '95783d18b77a1175cdaa465f441fcb3b740bc792a1364e50f805e7ce71d2993f', must be activated (ACTIVATION_REQUIRED)
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T16:50:27.646Z WARN    :HLFQueryHandler          :queryChaincode()          query payload returned an error: Error: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '95783d18b77a1175cdaa465f441fcb3b740bc792a1364e50f805e7ce71d2993f', must be activated (ACTIVATION_REQUIRED) {}$
2019-06-24T16:50:27.646Z ERROR   :HLFConnection            :ping()                    {"message":"Error trying to ping. Error: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '95783d18b77a1175cdaa465f441fcb3b740bc792a1364e50f805e7ce71d2993f', must be activated (ACTIVATION_REQUIRED)","stack":"Error: Error trying to ping. Error: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '95783d18b77a1175cdaa465f441fcb3b740bc792a1364e50f805e7ce71d2993f', must be activated (ACTIVATION_REQUIRED)\n    at _checkRuntimeVersions.then.catch (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:886:34)\n    at <anonymous>"}$
2019-06-24T17:57:14.232Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T17:57:14.305Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T17:57:14.307Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T17:57:14.451Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T17:57:14.457Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string' {}$
2019-06-24T17:57:14.460Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string' {}$
2019-06-24T17:57:14.460Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string' {}$
2019-06-24T17:57:14.461Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string' {}$
2019-06-24T17:57:14.464Z ERROR   :HLFConnection            :invokeChainCode()         Failed to invoke business network with transaction id: 0dae7dbb0094c8bdd8b569da28f41855af2aac527b44f113721cefaf043a6846 {}$
2019-06-24T17:57:14.465Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'\nResponse from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'\nResponse from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'\nResponse from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'","stack":"Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'\nResponse from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'\nResponse from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'\nResponse from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'\n    at HLFConnection._validatePeerResponses (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:855:19)\n    at HLFConnection.invokeChainCode (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:1057:35)\n    at <anonymous>"}$
2019-06-24T18:01:01.690Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T18:01:01.784Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T18:01:01.797Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T18:01:01.811Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/fabric-client/lib/Peer.js:114:16
    at /home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:586:7 {}$
2019-06-24T18:01:01.812Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string' {}$
2019-06-24T18:01:01.812Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string' {}$
2019-06-24T18:01:01.812Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string' {}$
2019-06-24T18:01:01.812Z WARN    :HLFConnection            :_validatePeerResponses()  Response from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string' {}$
2019-06-24T18:01:01.812Z ERROR   :HLFConnection            :invokeChainCode()         Failed to invoke business network with transaction id: 3c03d8cbbc620f0a72888703b6c5b2b71b5f44b1a045edaf48dfee32ea5e1e7d {}$
2019-06-24T18:01:01.813Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'\nResponse from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'\nResponse from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'\nResponse from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'","stack":"Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'\nResponse from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'\nResponse from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'\nResponse from attempted peer comms was an error: Error: transaction returned with failure: AccessException: Participant 'org.hyperledger.composer.system.NetworkAdmin#alice' does not have 'CREATE' access to resource 'org.gateway.datasensor.DataSensor#string'\n    at HLFConnection._validatePeerResponses (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:855:19)\n    at HLFConnection.invokeChainCode (/home/peer1/.nvm/versions/node/v8.16.0/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:1057:35)\n    at <anonymous>"}$
